from pydantic import BaseModel, Field
from typing import List, Optional, Literal


class VulnerabilityResponse(BaseModel):
    """
    normalized vulnerability object returned by the api
    """

    id: str
    published: Optional[str] = None
    last_modified: Optional[str] = None
    status: Optional[str] = None
    description: Optional[str] = None
    severity: Optional[str] = None
    score: Optional[float] = None
    vendor: Optional[str] = None
    weaknesses: List[str] = Field(default_factory=list)
    products: List[str] = Field(default_factory=list)
    references: List[str] = Field(default_factory=list)


class ExtractRequest(BaseModel):
    """
    request body for entity extraction endpoint
    """
    text: str


class QueryRequest(BaseModel):
    """
    request body for natural language querying endpoint
    """
    question: str


class ExtractedEntities(BaseModel):
    """
    entities extracted from free text
    """
    cve_ids: List[str] = Field(default_factory=list)
    software: List[str] = Field(default_factory=list)
    vendor: List[str] = Field(default_factory=list)
    severity: List[str] = Field(default_factory=list)
    weakness: List[str] = Field(default_factory=list)


class QueryInterpretation(BaseModel):
    """
    structured interpretation generated by the llm
    """

    intent: Literal[
        "lookup_cve",
        "mitigation_lookup",
        "software_search",
        "severity_search",
        "weakness_search",
        "vendor_search",
        "advanced_search",
        "unknown",
    ]
    cve_id: Optional[str] = None
    software: Optional[str] = None
    vendor: Optional[str] = None
    severity: Optional[str] = None
    weakness: Optional[str] = None
    wants_mitigation: bool = False


class QueryResponse(BaseModel):
    """
    response returned by the qa endpoint
    """
    interpretation: QueryInterpretation
    results: List[VulnerabilityResponse] = Field(default_factory=list)
    explanation: Optional[str] = None
